apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: postgres


# kubectl exec -it [pod-name] --  psql -h localhost -U admin --password -p 5432 postgresdb
