apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-nfs
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: unique-volumeid  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: 1-5870b179-playground-sandbox  # optional, only set this when storage account is not in the same resource group as node
      shareName: leonsshare01
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
    - dir_mode=0700
    - file_mode=0700
    - uid=999
    - gid=999
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl