apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-nfs
  volumeName: azurefile-nfs
  resources:
    requests:
      storage: 5Gi